delimiter |
CREATE  EVENT `remove_old_session1`
	ON SCHEDULE
		EVERY 1 MINUTE STARTS '2019-12-16 01:15:12'
	ON COMPLETION PRESERVE
	ENABLE
	COMMENT ''
 DO BEGIN
	DELETE FROM HappyToHelp.sessions WHERE UNIX_TIMESTAMP(CURRENT_TIMESTAMP) - lastActivity > 3600;
END |
delimiter ;
